language: minimal

services:
  - docker

before_install:
  - docker pull escabe/pvr.jellyfin-build:18.1

install: skip

script:
  - mkdir $TRAVIS_BUILD_DIR/output
  - docker run -v $TRAVIS_BUILD_DIR/output:/output escabe/pvr.jellyfin-build:18.1
  
